'use strict';
const q=s=>document.querySelector(s);
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storageKey='agromatch-prototype-v1';
function readCommunity(){try{return JSON.parse(localStorage.getItem(storageKey))||{};}catch{return {};}}
const sampleFarms=[
 ['Finca La Ladera','Cartago','Tomate','tomatoes.jpg',9.86,-83.91],
 ['Finca Los Altos','San José','Aguacate Hass','avocado.jpg',9.91,-84.08],
 ['Huerta El Roble','Cartago','Zanahoria','carrots.jpg',9.93,-83.87],
 ['Finca Río Claro','Limón','Banano','bananas.jpg',9.99,-83.04],
 ['Huerta La Esperanza','Alajuela','Hortalizas','vegetables.jpg',10.02,-84.21],
 ['Finca El Encuentro','Heredia','Tomate para procesamiento','tomatoes.jpg',10.00,-84.12]
].map((f,i)=>({id:'farm-'+i,name:f[0],province:f[1],specialty:f[2],image:f[3],lat:f[4],lng:f[5],role:'Agricultor',zone:'Ubicación ilustrativa',bio:'Perfil de ejemplo para conocer la finca y explorar sus cosechas. Este negocio es ficticio.',delivery:'Retiro en finca, sujeto a coordinación. Sin entregas reales en esta demostración.',demo:true}));
const sampleDistributors=[
 {id:'distribution-0',name:'Distribución Valle Verde',province:'Alajuela',specialty:'Distribución de hortalizas en el Valle Central',lat:10.01,lng:-84.24},
 {id:'distribution-1',name:'Enlace del Caribe',province:'Limón',specialty:'Distribución de frutas en la región Caribe',lat:10.05,lng:-83.1}
].map(p=>({...p,role:'Distribuidor',image:'vegetables.jpg',zone:'Ubicación ilustrativa',bio:'Distribuidor ficticio para mostrar su cobertura y servicios. No es un proveedor contratado.',delivery:'Cobertura y precio de transporte por acordar. No se contrata ni se cobra transporte en este prototipo.',demo:true}));
function profiles(){const s=readCommunity();const saved=Array.isArray(s.profiles)?s.profiles:[];const inferred=(s.lots||[]).filter(l=>!sampleFarms.some(p=>p.name===l.farm)&&!saved.some(p=>p.name===l.farm)).map(l=>({id:'lot-'+l.id,name:l.farm,province:l.province,specialty:l.name,role:'Agricultor',image:'vegetables.jpg',bio:'Perfil creado a partir de un lote de prueba en este navegador.',delivery:l.description,inferred:true}));return [...saved,...inferred.filter((p,i,a)=>a.findIndex(x=>x.name===p.name)===i),...sampleFarms,...sampleDistributors];}
function distance(a,b){const rad=n=>n*Math.PI/180;const dlat=rad(b.lat-a.lat),dlng=rad(b.lng-a.lng);const h=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlng/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
let position=null,locationRequest=0;
function results(){let list=profiles().map(p=>({...p,distance:position&&Number.isFinite(p.lat)&&Number.isFinite(p.lng)?distance(position,p):null}));const term=q('#directory-search').value.trim(),role=q('#directory-role').value,province=q('#directory-province').value;list=list.filter(p=>(!term||AgroSearch.matches({name:p.name,description:p.specialty,province:p.province},term))&&(!role||p.role===role)&&(!province||p.province===province));if(position){const radius=q('#radius').value;list=list.filter(p=>radius==='all'||p.distance!==null&&p.distance<=Number(radius));list.sort((a,b)=>(a.distance??Infinity)-(b.distance??Infinity));}return list;}
function renderDirectory(){const list=results();q('#directory-count').textContent=list.length+' perfiles'+(position?' · Ordenados por distancia aproximada':'');q('#directory-grid').innerHTML=list.length?list.map((p,i)=>`<article class="farm-card"><img src="assets/${escapeHTML(p.image||'vegetables.jpg')}" alt="Imagen ilustrativa de cosechas" loading="lazy"><div class="farm-copy"><span class="farm-role">${escapeHTML(p.role)} · ${p.demo?'Ejemplo ficticio':'Perfil local de prueba'}</span><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.province)}${p.zone?' · '+escapeHTML(p.zone):''}</p><p>${escapeHTML(p.specialty)}</p>${position?`<p><strong>${p.distance===null?'Sin coordenadas':p.distance.toFixed(1)+' km en línea recta'}</strong>${p.demo?' · ubicación ficticia':''}</p>`:''}<button class="button outline" data-profile="${escapeHTML(p.id)}">Ver perfil${position?' · '+(i+1):''}</button></div></article>`).join(''):'<div class="directory-empty"><h3>No encontramos perfiles con estos filtros.</h3><p>Ampliá la distancia o elegí otra provincia. Los perfiles sin coordenadas aparecen al elegir «Sin límite».</p></div>';renderRadar(list);}
function renderRadar(list){q('#nearby-map').hidden=!position;if(!position)return;const points=list.filter(p=>p.distance!==null);const max=Math.max(1,...points.map(p=>p.distance));q('#radar').innerHTML='<circle cx="200" cy="140" r="115"/><circle cx="200" cy="140" r="58"/><path d="M200 20V260M80 140H320" stroke="#b7c8ad"/><circle class="radar-me" cx="200" cy="140" r="8"/><text x="212" y="158">Vos</text><text x="200" y="15" text-anchor="middle">Norte</text>'+points.map(p=>{const dy=p.lat-position.lat,dx=(p.lng-position.lng)*Math.cos(position.lat*Math.PI/180),angle=Math.atan2(dy,dx),r=115*p.distance/max,x=200+Math.cos(angle)*r,y=140-Math.sin(angle)*r;return `<a href="#profile" data-profile="${escapeHTML(p.id)}" aria-label="Ver perfil de ${escapeHTML(p.name)}"><circle class="radar-dot" cx="${x}" cy="${y}" r="14"/><text x="${x}" y="${y+4}" text-anchor="middle" style="fill:white;font-size:12px">${list.indexOf(p)+1}</text></a>`;}).join('');}
function showProfile(id){const p=profiles().find(p=>p.id===id||p.name===id);if(!p)return;const lots=(readCommunity().lots||[]).filter(l=>l.farm===p.name);q('#profile-content').innerHTML=`<img class="profile-photo" src="assets/${escapeHTML(p.image||'vegetables.jpg')}" alt="Cosechas ilustrativas"><p class="eyebrow">${escapeHTML(p.role)} · ${p.demo?'Ejemplo ficticio':'Prueba local'}</p><h2 id="profile-title">${escapeHTML(p.name)}</h2><p>${escapeHTML(p.province)}${p.zone?' · '+escapeHTML(p.zone):''}</p><h3>Quiénes somos</h3><p>${escapeHTML(p.bio)}</p><h3>Productos y servicios</h3><p>${escapeHTML(p.specialty)}</p><h3>Entrega y cobertura</h3><p>${escapeHTML(p.delivery)}</p><p class="commission-note">AgroMatch no cobra comisión por transacción. El transporte o los cargos externos, si corresponden, se acuerdan por separado.</p>${lots.length?'<h3>Lotes publicados en este navegador</h3><ul class="profile-lots">'+lots.map(l=>`<li>${escapeHTML(l.name)}</li>`).join('')+'</ul>':''}<div class="profile-actions">${p.role==='Agricultor'?`<a class="button" href="market.html?farm=${encodeURIComponent(p.name)}">Ver sus cosechas</a>`:''}${!p.demo?`<button class="button outline" data-edit="${escapeHTML(p.id)}">Editar perfil</button>`:''}</div><p>No hay identidad verificada ni contacto con este negocio. Perfil de demostración.</p>`;q('#profile-dialog').showModal();}
function editProfile(id){const p=profiles().find(x=>x.id===id);q('#profile-form').reset();q('#profile-error').textContent='';for(const name of ['id','name','role','province','zone','specialty','bio','delivery','lat','lng'])if(p&&q('#profile-form').elements[name])q('#profile-form').elements[name].value=p[name]??'';q('#profile-dialog').close();q('#edit-dialog').showModal();}
document.addEventListener('click',e=>{const profile=e.target.closest('[data-profile]');if(profile){e.preventDefault();showProfile(profile.dataset.profile);}const edit=e.target.closest('[data-edit]');if(edit)editProfile(edit.dataset.edit);if(e.target.closest('.close-profile'))e.target.closest('dialog').close();});
q('#create-profile').addEventListener('click',()=>editProfile());
for(const id of ['directory-search','directory-role','directory-province','radius'])q('#'+id).addEventListener(id==='directory-search'?'input':'change',renderDirectory);
q('#locate').addEventListener('click',()=>{if(!navigator.geolocation){q('#location-status').textContent='Este navegador no permite ubicación. Elegí una provincia.';return;}const request=++locationRequest;q('#locate').disabled=true;q('#location-status').textContent='Esperando permiso de ubicación…';setTimeout(()=>{if(request===locationRequest&&q('#locate').disabled){q('#locate').disabled=false;q('#location-status').textContent='No pudimos obtener tu ubicación todavía. Si el navegador muestra un aviso, aceptalo; si no, elegí una provincia.';}},15000);navigator.geolocation.getCurrentPosition(result=>{if(request!==locationRequest)return;position={lat:result.coords.latitude,lng:result.coords.longitude};q('#locate').disabled=false;q('#clear-location').hidden=false;q('#location-status').textContent='Distancias aproximadas desde tu ubicación (precisión del dispositivo: '+Math.round(result.coords.accuracy)+' m). No son tiempos de viaje. Las fincas de ejemplo tienen coordenadas ficticias.';renderDirectory();},()=>{if(request!==locationRequest)return;q('#locate').disabled=false;q('#location-status').textContent='No pudimos obtener tu ubicación. Podés habilitar el permiso e intentar de nuevo o elegir una provincia.';},{enableHighAccuracy:false,timeout:12000,maximumAge:60000});});
q('#clear-location').addEventListener('click',()=>{locationRequest++;position=null;q('#locate').disabled=false;q('#clear-location').hidden=true;q('#location-status').textContent='Ubicación descartada. Podés seguir buscando por provincia.';renderDirectory();});
q('#profile-form').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(![f.name,f.specialty,f.bio,f.delivery].every(s=>s.trim())){q('#profile-error').textContent='Completá los campos sin dejarlos en blanco.';return;}if((f.lat==='')!==(f.lng==='')){q('#profile-error').textContent='Ingresá ambas coordenadas o dejá ambas vacías.';return;}const current=readCommunity(),saved=Array.isArray(current.profiles)?current.profiles:[];if([...sampleFarms,...sampleDistributors,...saved.filter(p=>p.id!==f.id)].some(p=>AgroSearch.normalize(p.name)===AgroSearch.normalize(f.name))){q('#profile-error').textContent='Ya existe un perfil con ese nombre. Elegí otro para distinguirlo.';return;}const old=profiles().find(p=>p.id===f.id);const p={...f,id:f.id||'profile-'+crypto.randomUUID(),name:f.name.trim(),image:'vegetables.jpg',lat:f.lat===''?null:Number(f.lat),lng:f.lng===''?null:Number(f.lng)};const next={cart:{},favorites:[],orders:[],lots:[],...current,profiles:[p,...saved.filter(x=>x.id!==p.id)]};if(old&&old.name!==p.name)next.lots=next.lots.map(l=>l.farm===old.name?{...l,farm:p.name}:l);try{localStorage.setItem(storageKey,JSON.stringify(next));}catch{q('#profile-error').textContent='No se pudo guardar. Revisá el espacio disponible del navegador.';return;}q('#edit-dialog').close();renderDirectory();showProfile(p.id);});
window.addEventListener('storage',e=>{if(e.key===storageKey){q('#profile-dialog').close();renderDirectory();}});
renderDirectory();const requested=new URLSearchParams(location.search).get('farm');if(requested)showProfile(requested);
