'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('es-CR',{style:'currency',currency:'CRC',maximumFractionDigits:0}).format(n);
const dateBase=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Costa_Rica',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const plusDay=n=>{const d=new Date(dateBase()+'T12:00:00');d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const displayDate=s=>new Intl.DateTimeFormat('es-CR',{day:'numeric',month:'short'}).format(new Date(s+'T12:00:00'));
const seed=[
 {id:'tomate',name:'Tomate de temporada',category:'Hortalizas',farm:'Finca La Ladera',province:'Cartago',price:750,stock:180,min:10,day:0,image:'tomatoes.jpg',description:'Tomate maduro para cocina y salsas. Lote de temporada, selección comercial y retiro coordinado en finca.'},
 {id:'aguacate',name:'Aguacate Hass',category:'Frutas',farm:'Finca Los Altos',province:'San José',price:1850,stock:90,min:5,day:1,image:'avocado.jpg',description:'Aguacate Hass de maduración progresiva. Presentación a granel, ideal para restaurantes y comercios.'},
 {id:'zanahoria',name:'Zanahoria fresca',category:'Hortalizas',farm:'Huerta El Roble',province:'Cartago',price:480,stock:240,min:10,day:0,image:'carrots.jpg',description:'Zanahoria de distintos calibres. Apta para cocina y procesamiento. Se coordina el retiro al confirmar disponibilidad.'},
 {id:'banano',name:'Banano de cosecha',category:'Frutas',farm:'Finca Río Claro',province:'Limón',price:390,stock:320,min:20,day:0,image:'bananas.jpg',description:'Banano amarillo de temporada para consumo y preparación. Entrega a granel, sujeto a revisión de madurez.'},
 {id:'mixto',name:'Selección de hortalizas',category:'Mixtos',farm:'Huerta La Esperanza',province:'Alajuela',price:690,stock:150,min:15,day:2,image:'vegetables.jpg',description:'Lote mixto de vegetales de temporada. La composición se confirma antes del retiro según la cosecha.'},
 {id:'tomate-industria',name:'Tomate para procesamiento',category:'Hortalizas',farm:'Finca El Encuentro',province:'Heredia',price:520,stock:260,min:25,day:1,image:'tomatoes.jpg',description:'Tomate de madurez avanzada para salsa y procesamiento oportuno. Requiere acordar la fecha de retiro.'}
].map(p=>({...p,date:plusDay(p.day)}));
const KEY='agromatch-prototype-v1';
const emptyState=()=>({cart:{},favorites:[],orders:[],lots:[]});
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(!s||!s.cart||!Array.isArray(s.favorites)||!Array.isArray(s.orders)||!Array.isArray(s.lots))return emptyState();return s;}catch{return emptyState();}}
let state=load(),category='Todos',view='explore',toastTimer;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast('No se pudo guardar en este navegador. La sesión sigue disponible.');}}
function products(){return [...state.lots,...seed].map(p=>({...p,available:Math.max(0,p.stock-state.orders.filter(o=>!o.cancelled).reduce((n,o)=>n+o.items.filter(i=>i.id===p.id).reduce((s,i)=>s+i.qty,0),0))}));}
function product(id){return products().find(p=>p.id===id);}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function favorite(id){if(!product(id))return;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();renderProducts();renderFavorites();}
function card(p){const saved=state.favorites.includes(p.id);const available=p.available>=p.min;return `<article class="product-card"><button class="product-image-button" data-detail="${esc(p.id)}" aria-label="Ver ${esc(p.name)}"><img src="assets/${esc(p.image)}" alt="${p.own?'Imagen ilustrativa de productos frescos':esc(p.name)}" loading="lazy"></button><span class="product-badge">${!available?'Agotado':p.date<=dateBase()?'Disponible hoy':displayDate(p.date)}</span><button class="favorite-button ${saved?'saved':''}" data-favorite="${esc(p.id)}" aria-label="${saved?'Quitar de':'Agregar a'} favoritos: ${esc(p.name)}" aria-pressed="${saved}">${saved?'♥':'♡'}</button><div class="product-content"><div class="product-farm"><a href="community.html?farm=${encodeURIComponent(p.farm)}" aria-label="Ver perfil de ${esc(p.farm)}">${esc(p.farm)}</a> · ${esc(p.province)}</div><button class="product-title" data-detail="${esc(p.id)}">${esc(p.name)}</button><div class="product-meta"><span>${p.available} kg disponibles</span><span>Mín. ${p.min} kg</span></div><div class="product-bottom"><span class="price">${money(p.price)}<small> / kg</small></span><button class="add-product" data-detail="${esc(p.id)}" aria-label="Seleccionar kilos de ${esc(p.name)}" ${available?'':'disabled'}>+</button></div></div></article>`;}
function filtered(){let list=products();const q=$('#search').value.trim();const province=$('#province').value;if(q)list=list.filter(p=>AgroSearch.matches(p,q));if(category!=='Todos')list=list.filter(p=>p.category===category);if(province)list=list.filter(p=>p.province===province);if($('#sort').value==='price')list.sort((a,b)=>a.price-b.price);if($('#sort').value==='soon')list.sort((a,b)=>a.date.localeCompare(b.date));return list;}
function renderProducts(){const list=filtered();const original=$('#search').value;const expanded=AgroSearch.canonical(original);$('#search-match').textContent=expanded!==AgroSearch.normalize(original)?'También buscamos: '+expanded+'.':'';$('#results-count').textContent=`${list.length} lotes · Datos de demostración`;$('#products').innerHTML=list.length?list.map(card).join(''):'<div class="empty"><strong>No encontramos ese lote.</strong><p>Probá con otro producto o ampliá los filtros.</p><button class="button outline" data-clear>Limpiar filtros</button></div>';}
function renderFavorites(){const list=products().filter(p=>state.favorites.includes(p.id));$('#favorites-grid').innerHTML=list.length?list.map(card).join(''):'<div class="empty"><strong>Tu próxima cosecha favorita.</strong><p>Tocá el corazón de un lote para guardarlo aquí.</p><button class="button" data-view="explore">Explorar cosechas</button></div>';}
function setView(next){if(!['explore','favorites','orders','sell'].includes(next))next='explore';view=next;$$('.market-view').forEach(el=>el.hidden=el.id!==next+'-view');$$('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===next);if(b.tagName==='BUTTON')b.setAttribute('aria-current',b.dataset.view===next?'page':'false');});if(next==='favorites')renderFavorites();if(next==='orders')renderOrders();if(next==='sell')renderSeller();window.scrollTo({top:0,behavior:'instant'});}
function showDetail(id){const p=product(id);if(!p)return;const remain=p.available-(state.cart[id]||0);$('#product-detail').innerHTML=`<img class="detail-photo" src="assets/${esc(p.image)}" alt="${esc(p.name)}"><p class="product-farm"><a href="community.html?farm=${encodeURIComponent(p.farm)}">${esc(p.farm)}</a> · ${esc(p.province)} · Lote de demostración</p><h2 id="product-title">${esc(p.name)}</h2><p>${esc(p.description)}</p><div class="detail-facts"><div><small>Precio por kilo</small><b>${money(p.price)}</b></div><div><small>Volumen disponible</small><b>${p.available} kg</b></div><div><small>Pedido mínimo</small><b>${p.min} kg</b></div><div><small>Disponible desde</small><b>${displayDate(p.date)}</b></div></div><form id="add-form"><label class="quantity-control">Cantidad (kg)<input name="qty" type="number" value="${p.min}" min="${p.min}" max="${Math.max(0,remain)}" step="1" required></label><p class="fine">Retiro coordinado en finca. ${state.cart[id]?`${state.cart[id]} kg ya están en tu carrito.`:''}</p><button class="button wide" ${remain<p.min?'disabled':''}>${remain<p.min?'Sin volumen adicional disponible':'Agregar al carrito'}</button></form>`;$('#add-form').addEventListener('submit',e=>{e.preventDefault();const qty=Number(new FormData(e.target).get('qty'));try{addToCart(id,qty);$('#product-dialog').close();toast(`${qty} kg agregados a tu pedido.`);}catch(err){toast(err.message);}});$('#product-dialog').showModal();}
function addToCart(id,qty){const p=product(id);if(!p||!Number.isInteger(qty)||qty<p.min||qty+(state.cart[id]||0)>p.available)throw new Error('Revisá el mínimo y los kilos disponibles.');state.cart[id]=(state.cart[id]||0)+qty;save();renderCartCount();return {id,quantity:state.cart[id]};}
function renderCartCount(){$('#cart-count').textContent=Object.keys(state.cart).length;$('#cart-open').setAttribute('aria-label',`Abrir carrito: ${Object.keys(state.cart).length} lotes`);}
function cartEntries(){return Object.entries(state.cart).map(([id,qty])=>({p:product(id),qty})).filter(x=>x.p&&x.qty>0);}
function renderCart(){const list=cartEntries();$('#cart-items').innerHTML=list.length?list.map(({p,qty})=>`<div class="cart-line"><img src="assets/${esc(p.image)}" alt=""><div><h3>${esc(p.name)}</h3><small>${money(p.price)} / kg · ${esc(p.province)}</small><div class="qty-buttons"><button data-qty="${esc(p.id)}" data-change="-1" aria-label="Restar un kilo de ${esc(p.name)}" ${qty<=p.min?'disabled':''}>−</button><span>${qty} kg</span><button data-qty="${esc(p.id)}" data-change="1" aria-label="Sumar un kilo de ${esc(p.name)}" ${qty>=p.available?'disabled':''}>+</button><button class="remove" data-remove="${esc(p.id)}" aria-label="Quitar ${esc(p.name)}">Quitar</button></div></div><strong>${money(p.price*qty)}</strong></div>`).join(''):'<div class="empty"><strong>Tu carrito está vacío.</strong><p>Elegí una cosecha y la cantidad que necesitás.</p></div>';$('#checkout-section').hidden=!list.length;$('#cart-total').textContent=money(list.reduce((s,{p,qty})=>s+p.price*qty,0));const minDate=list.reduce((d,{p})=>p.date>d?p.date:d,dateBase());$('#pickup-date').min=minDate;if(!$('#pickup-date').value||$('#pickup-date').value<minDate)$('#pickup-date').value=minDate;$('#checkout-error').textContent='';renderCartCount();}
function paymentLabel(o){if(!o.payment)return 'Pago pendiente al retirar';if(o.payment.method==='sinpe')return o.payment.status==='verified'?'SINPE verificado (simulación)':o.payment.status==='rejected'?'Comprobante rechazado (simulación)':o.payment.receipt?'Comprobante pendiente de revisión':'Falta adjuntar comprobante';if(o.payment.method==='card')return 'Tarjeta aprobada (simulación)';return o.payment.status==='verified'?'Pago recibido (simulación)':'Pago pendiente al retirar';}
function renderOrders(){const steps=['Confirmado','En preparación','Listo para retiro','Retirado'];$('#orders-list').innerHTML=state.orders.length?state.orders.map(o=>`<article class="order-card"><div class="order-top"><div><h3>Pedido ${esc(o.code)}</h3><small class="fine">Retiro propuesto: ${displayDate(o.pickup)}</small></div><span class="order-status">${o.cancelled?'Cancelado':steps[o.step]} · Demo</span></div><p class="order-lines">${o.items.map(i=>`${esc(i.name)} · ${i.qty} kg`).join('<br>')}</p><p class="payment-status">${o.cancelled?'Pedido cancelado. No se realizó un cobro.':paymentLabel(o)}</p>${o.cancelled?'':`<ol class="order-progress">${steps.map((s,i)=>`<li class="${i<=o.step?'done':''}">${s}</li>`).join('')}</ol>`}<div class="order-footer"><strong>Total: ${money(o.total)}</strong><span class="fine">Comisión AgroMatch: ₡0</span>${!o.cancelled&&o.step<3?`<button class="button small" data-advance="${esc(o.id)}">Simular: ${steps[o.step+1].toLowerCase()}</button>`:''}</div><div class="order-actions">${!o.cancelled&&o.payment?.method==='sinpe'?`<button class="button outline" data-upload="${esc(o.id)}">${o.payment.receipt?'Reemplazar':'Adjuntar'} comprobante</button>`:''}${o.payment?.receipt?`<button class="button outline" data-download="${esc(o.id)}">Descargar comprobante</button>`:''}${!o.cancelled&&o.step<3?`<button class="button outline" data-cancel="${esc(o.id)}">Cancelar pedido de prueba</button>`:''}</div><p class="fine">${o.payment?.receipt?'Archivo: '+esc(o.payment.receipt.name)+'. ':''}Pedido de demostración. No se contactó a una finca ni se realizó un cobro.</p></article>`).join(''):'<div class="empty"><strong>Tu primer match está por llegar.</strong><p>Agregá una cosecha al carrito para empezar.</p><button class="button" data-view="explore">Buscar cosechas</button></div>';}
function renderSeller(){if(window.renderSales)window.renderSales();$('#seller-total').textContent=state.lots.length+' lotes';$('#seller-list').innerHTML=state.lots.map(l=>`<div class="seller-lot"><strong>${esc(l.name)}</strong><span>${product(l.id).available} kg · ${money(l.price)} / kg</span><button data-delete-lot="${esc(l.id)}">Retirar del catálogo</button></div>`).join('');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)setView(b.dataset.view);if(b.dataset.detail)showDetail(b.dataset.detail);if(b.dataset.favorite)favorite(b.dataset.favorite);if(b.hasAttribute('data-clear')){$('#search').value='';$('#province').value='';category='Todos';$$('[data-category]').forEach(x=>{x.classList.toggle('active',x.dataset.category==='Todos');x.setAttribute('aria-pressed',String(x.dataset.category==='Todos'));});renderProducts();}if(b.dataset.category){category=b.dataset.category;$$('[data-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderProducts();}if(b.classList.contains('close-dialog'))b.closest('dialog').close();if(b.dataset.remove){delete state.cart[b.dataset.remove];save();renderCart();}if(b.dataset.qty){const id=b.dataset.qty;const p=product(id);const n=state.cart[id]+Number(b.dataset.change);if(p&&n>=p.min&&n<=p.available){state.cart[id]=n;save();renderCart();}}if(b.dataset.advance){const o=state.orders.find(o=>o.id===b.dataset.advance);if(o&&o.step<3){o.step++;save();renderOrders();toast('Etapa de demostración actualizada.');}}if(b.dataset.deleteLot){const id=b.dataset.deleteLot;state.lots=state.lots.filter(x=>x.id!==id);delete state.cart[id];state.favorites=state.favorites.filter(x=>x!==id);save();renderAll();toast('Lote retirado del catálogo local.');}});
$('#cart-open').addEventListener('click',()=>{renderCart();$('#cart-dialog').showModal();});
$('#search').addEventListener('input',renderProducts);$('#province').addEventListener('change',renderProducts);$('#sort').addEventListener('change',renderProducts);
$('#checkout-form').addEventListener('submit',async e=>{
 e.preventDefault();const submit=e.target.querySelector('button[type=submit]');if(submit.disabled)return;
 const list=cartEntries();if(!list.length)return;const pickup=$('#pickup-date').value;
 if(pickup<$('#pickup-date').min){$('#checkout-error').textContent='Elegí una fecha posterior a la disponibilidad de todos los lotes.';return;}
 if(list.some(({p,qty})=>!Number.isInteger(qty)||qty<p.min||qty>p.available)){$('#checkout-error').textContent='La disponibilidad cambió. Ajustá las cantidades del carrito.';return;}
 const method=new FormData(e.target).get('payment');
 if(method==='card'&&$('#card-result').value==='declined'){$('#checkout-error').textContent='La tarjeta de prueba fue rechazada. Tu carrito sigue guardado; elegí otro método o probá un resultado aprobado.';return;}
 submit.disabled=true;const id=crypto.randomUUID?.()||String(Date.now());let receipt;
 try{
  const file=$('#checkout-receipt').files[0];if(method==='sinpe'&&file){await AgroReceipts.put(id,file);receipt={name:file.name,size:file.size,type:file.type};}
  const order={id,code:'AM-'+id.replace(/-/g,'').slice(0,6).toUpperCase(),pickup,step:0,total:list.reduce((s,{p,qty})=>s+p.price*qty,0),items:list.map(({p,qty})=>({id:p.id,name:p.name,farm:p.farm,qty,price:p.price})),payment:{method,status:method==='card'?'simulated-approved':'pending',...(receipt?{receipt}:{})}};
  const next={...state,orders:[order,...state.orders],cart:{}};
  try{localStorage.setItem(KEY,JSON.stringify(next));}catch{if(receipt)await AgroReceipts.remove(id);throw new Error('No pudimos guardar el pedido. Liberá espacio en el navegador; tu carrito no se borró.');}
  state=next;$('#cart-dialog').close();e.target.reset();$('#receipt-selection').textContent='';if(window.updatePaymentPanels)window.updatePaymentPanels();renderAll();setView('orders');toast('Pedido de prueba guardado. No se realizó un cobro.');
 }catch(err){$('#checkout-error').textContent=err.message;}finally{submit.disabled=false;}
});
$('#sell-form').elements.date.min=dateBase();$('#sell-form').elements.date.value=dateBase();
$('#sell-form').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const stock=Number(d.stock),price=Number(d.price),min=Number(d.min);if(!d.name.trim()||!d.farm.trim()||!d.description.trim()||![stock,price,min].every(Number.isInteger)||min>stock||stock<1||price<1||min<1||d.date<dateBase()){$('#sell-error').textContent='Revisá los datos: el mínimo no puede superar los kilos disponibles y la fecha debe ser vigente.';return;}state.lots.unshift({id:'local-'+(crypto.randomUUID?.()||Date.now()),name:d.name.trim(),category:d.category,province:d.province,farm:d.farm.trim(),description:d.description.trim(),stock,price,min,date:d.date,image:'vegetables.jpg',own:true});save();e.target.reset();e.target.elements.date.value=dateBase();$('#sell-error').textContent='';renderAll();toast('Tu lote de prueba ya está en el mercado.');});
$('#reset-demo').addEventListener('click',()=>$('#reset-dialog').showModal());
const mobileReset=document.createElement('button');mobileReset.type='button';mobileReset.className='button outline';mobileReset.textContent='Borrar mis datos de prueba';mobileReset.style.marginTop='20px';mobileReset.addEventListener('click',()=>$('#reset-dialog').showModal());$('.seller-summary').append(mobileReset);
$('#confirm-reset').addEventListener('click',async()=>{try{await AgroReceipts.clear();}catch{toast('No se pudieron borrar los comprobantes. Intentá de nuevo.');return;}state=emptyState();save();$('#reset-dialog').close();renderAll();toast('Datos de prueba eliminados.');});
function renderAll(){renderProducts();renderFavorites();renderOrders();renderSeller();renderCartCount();}
window.addEventListener('storage',e=>{if(e.key===KEY){state=load();renderAll();if($('#cart-dialog').open)renderCart();}});
const params=new URLSearchParams(location.search);
const requestedDevice=params.get('device');
const platform=requestedDevice==='ios'||requestedDevice==='android'?requestedDevice:/Android/i.test(navigator.userAgent)?'android':/iPhone|iPad|iPod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)?'ios':'web';
document.body.classList.add('platform-'+platform);
renderAll();setView(params.get('view')||'explore');
