const {chromium,devices}=require('playwright');
const assert=require('node:assert/strict');
const base=process.env.AGRO_TEST_URL||'http://127.0.0.1:8766/';
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.AGRO_BROWSER_CHANNEL||'msedge'});
 const context=await browser.newContext({...devices['iPhone 13']});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'market.html');
 await page.locator('#search').fill('paltas hass');assert.equal(await page.locator('#products .product-card').count(),1);assert.match(await page.locator('#search-match').textContent(),/aguacate/);
 await page.locator('#products .product-title').click();await page.locator('#add-form input').fill('6');await page.locator('#add-form button').click();await page.locator('#cart-open').click();
 await page.locator('[data-change="1"]').click();assert.match(await page.locator('.qty-buttons span').textContent(),/7 kg/);
 await page.locator('[data-change="-1"]').click();assert.match(await page.locator('.qty-buttons span').textContent(),/6 kg/);
 await page.locator('[data-remove]').click();assert.match(await page.locator('#cart-items').textContent(),/vacío/);await page.locator('#cart-dialog .close-dialog').click();
 async function addAvocado(){await page.locator('#products .product-title').click();await page.locator('#add-form button').click();await page.locator('#cart-open').click();await page.locator('#checkout-form input[type=checkbox]').check();}
 await addAvocado();await page.locator('input[value=card]').check();await page.locator('#card-result').selectOption('declined');await page.locator('#checkout-form button[type=submit]').click();assert.match(await page.locator('#checkout-error').textContent(),/rechazada/);assert(await page.locator('#cart-dialog').isVisible());
 await page.locator('input[value=sinpe]').check();await page.locator('#checkout-form button[type=submit]').click();await page.waitForSelector('.order-card');assert.match(await page.locator('.payment-status').textContent(),/Falta adjuntar/);
 await page.locator('[data-upload]').click();await page.locator('#order-receipt').setInputFiles({name:'incorrecto.txt',mimeType:'text/plain',buffer:Buffer.from('texto')});await page.locator('#receipt-form button').click();await page.waitForFunction(()=>document.querySelector('#order-receipt-error').textContent.length>0);assert.match(await page.locator('#order-receipt-error').textContent(),/válido/);
 const pdf={name:'comprobante-ejemplo.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n1 0 obj\n<<>>\nendobj\n%%EOF')};
 await page.locator('#order-receipt').setInputFiles(pdf);await page.locator('#receipt-form button').click();await page.waitForFunction(()=>!document.querySelector('#receipt-dialog').open);assert.match(await page.locator('.payment-status').textContent(),/pendiente de revisión/);
 await page.reload();await page.locator('.bottom-nav [data-view=orders]').click();assert.match(await page.locator('.order-card').textContent(),/comprobante-ejemplo.pdf/);assert.equal(await page.evaluate(async()=>{const db=await new Promise(r=>{const q=indexedDB.open('agromatch-receipts');q.onsuccess=()=>r(q.result);});return new Promise(r=>{const req=db.transaction('receipts').objectStore('receipts').count();req.onsuccess=()=>{db.close();r(req.result);};});}),1);
 await page.locator('.bottom-nav [data-view=sell]').click();await page.locator('[data-verify]').click();assert.match(await page.locator('#sales-list').textContent(),/verificado/);await page.locator('.bottom-nav [data-view=orders]').click();await page.locator('[data-cancel]').click();await page.locator('#cancel-order-confirm').click();await page.waitForFunction(()=>!document.querySelector('#cancel-order-dialog').open);assert.match(await page.locator('.order-status').textContent(),/Cancelado/);
 await page.locator('.bottom-nav [data-view=explore]').click();await page.locator('#search').fill('aguacate');assert.match(await page.locator('#products .product-meta').textContent(),/90 kg/);
 await addAvocado();await page.locator('input[value=card]').check();await page.locator('#card-result').selectOption('approved');await page.locator('#checkout-form button[type=submit]').click();await page.waitForSelector('.order-card');assert.match(await page.locator('.payment-status').first().textContent(),/Tarjeta aprobada/);
 await page.locator('.bottom-nav [data-view=sell]').click();await page.locator('#sell-form [name=name]').fill('Palta criolla');await page.locator('#sell-form [name=farm]').fill('Finca de prueba');await page.locator('#sell-form [name=description]').fill('Lote fresco');await page.locator('#sell-form button[type=submit]').click();await page.locator('.bottom-nav [data-view=explore]').click();await page.locator('#search').fill('aguacate');assert.equal(await page.locator('#products .product-card').count(),2);
 await page.locator('.reading-toggle').click();assert(await page.locator('body').evaluate(e=>e.classList.contains('large-text')));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.goto(base);assert.equal(await page.locator('.chapter-number').count(),0);assert.equal(await page.locator('.harvest-stop').count(),3);await page.locator('[data-story="2"]').click();await page.waitForTimeout(900);assert.equal(await page.locator('[data-story="2"]').getAttribute('aria-current'),'step');
 await page.screenshot({path:process.env.AGRO_SCREENSHOT||'work/agro-story-new.png',fullPage:true});
 assert.deepEqual(errors,[]);await context.close();
 const desktop=await browser.newPage();for(const width of [320,390,768,1024,1440]){await desktop.setViewportSize({width,height:900});for(const route of ['', 'market.html']){await desktop.goto(base+route);assert(await desktop.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${route} overflow at ${width}`);}}
 await browser.close();console.log('PASS: aliases, cart add/remove/quantities, rejected/approved card, pending SINPE, file validation, receipt persistence, seller review, cancellation/inventory, seller aliases, large text, story indicators, 5 viewport widths, no JS errors.');
})().catch(error=>{console.error(error);process.exit(1);});
